# 服务端口
server:
  port: 8082

# 服务应用名称
spring:
  application:
    name: customer-server
# eureka config
eureka:
  instance:
    # 使用IP进行注册
    prefer-ip-address: true
  client:
    # 注册地址
    service-url:
      defaultZone: http://localhost:8080/eureka/

