# 服务端口
server:
  port: 8081

# 服务应用名称
spring:
  application:
    name: provider-server
# eureka config
eureka:
  instance:
    # 使用IP进行注册
    prefer-ip-address: true
  client:
    # 注册地址
    service-url:
      defaultZone: http://localhost:8080/eureka/

feign:
  hystrix:
    # 开启断路器
    enabled: true
