# 服务端口
server:
  port: 8080

# 服务应用名称
spring:
  application:
    name: eureka-server

# eureka config
eureka:
  instance:
    # eureka 主机名
    hostname: eureka-server
  client:
    # false代表不向注册中心注册自己
    register-with-eureka: false
    # 是否需要从注册中心检索获取服务的注册信息。默认值为true
    # 单机版的可设置成false，集群版的由于需要同步其他节点的服务注册数据，故设成true
    fetch-registry: false
    # 提供者和消费者的注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 是否开启自我保护模式，默认值true
    # eureka server默认在运行期间会去统计心跳失败比例在 15 分钟之内是否低于 85%，如果低于 85%，
    # Eureka Server 会将这些实例保护起来，让这些实例不会过期，
    # 但是在保护期内如果服务刚好这个服务提供者非正常下线了，此时服务消费者就会拿到一个无效的服务实例，此时会调用失败
    #设置为false可以确保注册中心中不可用的实例被及时的剔除。
    enable-self-preservation: false
    # 清理无效节点的时间间隔，缺省 (1000*60)ms
    eviction-interval-timer-in-ms: 6000
    # 当获取不到对应实例时，需要等待的时间，缺省 (1000*60*5)ms
    wait-time-in-ms-when-sync-empty: 6000

